[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools>=75.3",
    "wheel",
]

[tool.cibuildwheel]
enable = ["cpython-freethreading"]

[tool.cibuildwheel.macos]
archs = "x86_64 arm64"