MESSAGE(PEMJA_ROOT_DIR:"${PEMJA_ROOT_DIR}")
SET(DEP_INSTALL_DIR "${PEMJA_ROOT_DIR}/pemja_dep_install")
MESSAGE(DEP_INSTALL_DIR:"${DEP_INSTALL_DIR}")
set(PYTHON_INCLUDE_DIR "${DEP_INSTALL_DIR}/include/python3.9")
set(PYTHON_LIBRARY "${DEP_INSTALL_DIR}/lib/libpython3.9.dylib")

set(Python_FOUND TRUE)
set(Python_INCLUDE_DIRS ${PYTHON_INCLUDE_DIR})
set(Python_LIBRARIES ${PYTHON_LIBRARY})
